### ISSUE TITLE
It's now "OR" on the required libs

### ISSUE THREAD

**Issue by phackwer** [stevelacy/msi-keyboard-gui#13]
On Ubuntu, I was required to install both the libs to compile the application.

Install the required libraries for your OS: libusb-dev AND libusb-1.0-0-dev

**Comment by stephenlacy** [comment]
And or or?

**Comment by JuanCAlpizar** [comment]
For Red Hat based systems the package is called `libusb-devel`, in case you wanna add it to the readme :) and I think he means you need both (aka you need to change the "or" for an "and" in the requirements section of the readme).

Mine refused to install `node-hid` just with `libusb`installed (the equivalent to `libusb-1.0.0-dev`), in order to install it I had to install `libusb-devel` as well and then everything ran with no errors.

**Comment by stephenlacy** [comment]
Sounds good, want to send a PR with a note under it for fedora?

**Comment by JuanCAlpizar** [comment]
Will do in a while when I get free time for it, I'm working on another repository at the moment :+1:
